name: Continuous Integration

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Test Local Action
        id: test-action-merge-develop-to-current-branch
        uses: ./
        with:
          github_token: ${{ secrets.PIPELINE_GITHUB_TOKEN }}
          repo_owner: 3dwardch3ng
          repo_name: 'github-pull-request'
          source_branch: 'develop'
          target_branch: '11-add-action-test-in-the-ci-pipeline'
          pr_title: 'merge from develop'
          require_middle_branch: true
          auto_merge: false
          max_merge_retries: 10